theme: jekyll-theme-minimal
title: Robyn Burger
description: Hello! My name is Robyn. I am a rising senior at Cornell University, studying CS and math.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
logo: images/pfp.JPG

